### PR TITLE
Merge lsqlite-only branch into master

### PR DESCRIPTION
**Pull request by peterbell10**

### CODE REVIEW

**Comment by tigerw** [comment]
I'm getting a build error on VS

```
cuberite\lib\sqlite\lsqlite3.c(47): fatal error C1083: Cannot open include file: 'lua.h': No such file or directory
```

**Comment by peterbell10** [comment]
You need the accompanying fix in the `lua` CMake.

**Comment by tigerw** [comment]
Now I get
```
Cannot open include file: 'sqlite3.h'
```

**Comment by peterbell10** [comment]
The problem is your changes to the cuberite CMake.

**Comment by tigerw** [comment]
SQLiteCpp made their sqlite3 private: https://github.com/SRombauts/SQLiteCpp/blob/master/sqlite3/CMakeLists.txt#L15

Can you add a target_include_directories(lsqlite PRIVATE ../SQLiteCpp/sqlite3)?

**Comment by peterbell10** [comment]
https://github.com/cuberite/SQLiteCpp/commit/829d549af3a11e24fcb0b99090837dac9a9aae4f

**Pull request merged**
